package Algorithms;

public enum AlgorithmType {
    RING,
    RING_TWO_PORT,
    RECURSIVE_DOUBLING_LATENCY,
    RECURSIVE_DOUBLING_BANDWIDTH,
    RECURSIVE_DOUBLING_BANDWIDTH_TWO_PORT,
    SWING_LATENCY,
    SWING_BANDWIDTH,
    SWING_LATENCY_TWO_PORT,
    SWING_BANDWIDTH_TWO_PORT,
    TRIVANCE_LATENCY,
    TRIVANCE_BANDWIDTH,
    SPLIT
}
